spring.application.name=EmployeeManagementSystem
spring.datasource.url=jdbc:mysql://localhost:3306/emp_db
spring.datasource.username=root
spring.datasource.password=shivam@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
